app_commands = {
    # System Applications
    "notepad": "notepad",
    "calculator": "calc",
    "file explorer": "explorer",
    "paint": "mspaint",
    "command prompt": "cmd",
    "task manager": "taskmgr",
    "ms word": "winword",
    "ms excel": "excel",
    "ms powerpoint": "powerpnt",
    "control panel": "control",
    "settings": "start ms-settings:",
    "snipping tool": "snippingtool",
    "camera": "start microsoft.windows.camera:",
    "wordpad": "write",
    "event viewer": "eventvwr",
    "device manager": "devmgmt.msc",
    "disk management": "diskmgmt.msc",
    "registry editor": "regedit",
    "system information": "msinfo32",
    "task manger":"taskmgr",
    "windows defender": "windowsdefender:",
    # Popular Websites
    "google": "https://www.google.com",
    "facebook": "https://www.facebook.com",
    "linkedin": "https://www.linkedin.com",
    "instagram": "https://www.instagram.com",
    "youtube": "https://www.youtube.com",
    "twitter": "https://www.twitter.com",
    "github": "https://www.github.com",
    "stackoverflow": "https://stackoverflow.com",
    "gmail": "https://mail.google.com",
    "whatsapp web": "https://web.whatsapp.com",
    "reddit": "https://www.reddit.com",
    "quora": "https://www.quora.com",
    "amazon": "https://www.amazon.com",
    "netflix": "https://www.netflix.com",
    "spotify": "https://www.spotify.com",
    "news": "https://www.bbc.com/news"
}
